version: '3.7'
services:
  mnist-cpu:
    build:
      context: .
      dockerfile: Dockerfile-CPU
    image: mnist_cnn_cuda:${TAG}
  mnist-cpu-train:
    image: mnist_cnn_cuda:${TAG}
    volumes:
      - $HOME/.keras:/root/.keras
      - ./mnist_py:/mnist_py
    command: >
      python /mnist_py/train.py